[package]
name = "script-bench"
version = "0.1.0"
edition = "2021"
authors = ["Aleksandr Orlenko <zxteam@pm.me>"]

[features]
mlua_lua54 = ["mlua/lua54", "mlua/vendored"]
mlua_luau = ["mlua/luau"]
boa = ["boa_engine", "boa_gc", "gc"]

[dependencies]
rand = "0.8"
mlua = { version = "0.8.4", optional = true }
rlua = { version = "0.19.4", optional =  true }
rhai = { version = "1.10.1", optional = true }
rune = { version = "0.12.0", optional = true }
boa_engine = { version = "0.16.0", optional = true, features = ["console"] }
boa_gc = { version = "0.16.0", optional = true }
gc = { version = "0.4.1", optional = true }
itertools = "0.10"

[dev-dependencies]
criterion = { version = "0.4" }

[profile.bench]
lto = true
codegen-units = 1

[[bench]]
name = "boa"
harness = false
required-features = ["boa"]

[[bench]]
name = "mlua_lua54"
harness = false
required-features = ["mlua_lua54"]

[[bench]]
name = "mlua_luau"
harness = false
required-features = ["mlua_luau"]

[[bench]]
name = "rlua"
harness = false
required-features = ["rlua"]

[[bench]]
name = "rhai"
harness = false
required-features = ["rhai"]

[[bench]]
name = "rune"
harness = false
required-features = ["rune"]
